#!/usr/bin/env bash
#===================================================================================
#     FILE: exam/backup/del
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Delete exam(s) backup"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: backup number
	read_param "$script_id" 1 "Backup number" "" "^[0-9]+$"
    return
fi


#=== EXEC SCRIPT ===================================================================
enum="$1"
labadmin_cache_path="/home/.labadmin-cache/"			# Labadmin exam cache path

# SHOW LIST
backups_list="$(ls -d "${labadmin_cache_path}/EXAM_"* 2>/dev/null)"
if [ $? -ne 0 ]; then
    echo "No exams saved"
    exit 0
fi


n=1
m="${S_B}ID DIR SIZE DAYS-AGO HOME SCREENSHOTS${S_R}\n"
IFS=$'\n'
for d in $backups_list; do
    l="[$n] $(basename "$d") $(du -sh "$d" | cut -f1) $((($(date +%s)-$(date -r "$d" +%s))/86400))  $(du -sh "${d}/home/" 2>/dev/null| cut -f1)  $(du -sh "${d}/screenshots/" 2>/dev/null| cut -f1)\n"
	if [ "$n" -eq "$enum" ]; then
		m="${m}${C_BR}${l}${S_R}"
		edir="$d"
		enum=0
	else
		m="${m}${l}"
		n=$((n+1))
	fi
done
echo
echo -e "$m" | column -t | sed '1a----------------------------------------------------------------------------'
echo


# CHECK SELECTED BACKUP FILE
[ ! -e "$edir" ] && labadmin_error "ERROR: can't access dir $edir" 1

# DELETE BACKUP
echo
echo rm -rfv "$edir"
