#!/usr/bin/env bash
#===================================================================================
#     FILE: exam/backup/download
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Download exam backup to local machine"
	script_type="local"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="7za(p7zip-full|p7zip) md5sum(coreutils)"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: backup number
	read_param "$script_id" 1 "Backup number" "" "^[0-9]+$"
	read_param "$script_id" 2 "Destination path (default $HOME)" "$HOME" ""
    return
fi


#=== EXEC SCRIPT ===================================================================
enum="$1"
dest="$(eval echo "$2")"								# Resolve scape characteres like \ ,*, etc.
labadmin_cache_path="/home/.labadmin-cache/"			# Labadmin exam cache path

# CHECK DEST
[ ! -w "$dest" ] || [ ! -w "$dest" ] && labadmin_error "Can't write in local path $dest" 1

# CHECK EXAM FILENAME
edir="$(labdmin_ssh_host_comm "${labadmin_nhost}" "ls -d \"${labadmin_cache_path}\"EXAM* | sed -n ${enum}p")"

[ ! "$edir" ] && labadmin_error "Can't access backup number $enum ($exam_backups)" 1

# DOWNLOAD FILE
dest="$dest/$(basename "$edir")_HOST${labadmin_nhost}"
mkdir "$dest" || labadmin_error "Cant create dest dir: $dest" 1 
echo -e "Destination: ${S_B}$dest${S_R}"
echo "Downloading exam..."
labdmin_ssh_host_comm "${labadmin_nhost}" "tar -c -C \"$(dirname \"${edir}\")\" \"$(basename \"${edir}\")\" | pv -s $(du -sb \"${edir}\" | cut -f1)" | tar xv -C "$dest"



