#!/usr/bin/env bash
#===================================================================================
#     FILE: exam/backup/list
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="List all exam saved and hidden in root account"
	script_type="ssh"
	script_bg="sub"
    script_admindeps=""
    script_hostdeps=""
    load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    return
fi


#=== EXEC SCRIPT ===================================================================
labadmin_cache_path="/home/.labadmin-cache/"			# Labadmin exam cache path

# SHOW LIST
backups_list="$(ls -d "${labadmin_cache_path}/EXAM_"* 2>/dev/null)"
if [ $? -ne 0 ]; then
    echo "No exams saved"
    exit 0
fi

n=1
c="%-4s%-30s%-8s%-10s%-35s\n"
printf "${S_B}${c}${S_R}" "ID" "FILE" "SIZE" "DAYS-AGO" "PASSWORD (7za x <file> -p<pass>)"
IFS=$'\n\t'
for f in $backups_list; do
    efiles[$n]="$exam_backups/$f"
    bpass="$(echo "${efiles[$n]}" | md5sum | cut -f1 -d" ")"
    printf "$c" "[$n]" "$f" "$(du -sh "${efiles[$n]}" | cut -f1)" "$(( ($(date +%s)-$(date -r "${efiles[$n]}" +%s))/86400 ))" "$bpass"
    n=$(($n+1))
done

