#!/usr/bin/env bash
#===================================================================================
#     FILE: exam/backup/list
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="List all exam saved and hidden in root account"
	script_type="ssh"
	script_bg="sub"
    script_admindeps=""
    script_hostdeps=""
    load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    return
fi


#=== EXEC SCRIPT ===================================================================
labadmin_cache_path="/home/.labadmin-cache/"			# Labadmin exam cache path

# SHOW LIST
backups_list="$(ls -d "${labadmin_cache_path}/EXAM_"* 2>/dev/null)"
if [ $? -ne 0 ]; then
    echo "No exams saved"
    exit 0
fi

n=1
m="${S_B}ID DIR SIZE DAYS-AGO HOME SCREENSHOTS${S_R}\n"
IFS=$'\n'
for d in $backups_list; do
    m="${m} [$n] $(basename "$d") $(du -sh "$d" | cut -f1) $((($(date +%s)-$(date -r "$d" +%s))/86400))  $(du -sh "${d}/home/" 2>/dev/null| cut -f1)  $(du -sh "${d}/screenshots/" 2>/dev/null| cut -f1)\n"
    n=$(($n+1))
done
echo -e "$m" | column -t
