#!/usr/bin/env bash
#===================================================================================
# LABADMIN INSTALLATION
#         FILE: install
#
#  DESCRIPTION: Install and check labadmin dependencies for admin and host
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#      VERSION: 2019.04
#      CREATED: 16.02.2017
#===================================================================================

#===============================================================================
#  LOAD LIBS
#===============================================================================
readonly labadmin_path="$(dirname $(readlink -f "${0}"))"                       # LABADMIN script root directory path
readonly lib_path="${labadmin_path}/lib/"                                       # LABADMIN LIB PATH
source "${lib_path}/labadmin_lib-admin"                                         # LABADMIN ADMIN VARIABLES AND FUNCTIONS
source "${lib_path}/labadmin_lib"												# LABADMIN GLOBAL VARIABLES AND FUNCTIONS
source "${lib_path}/labadmin_lib-script"										# LABADMIN SCRIPT MODULE
source "${lib_path}/labadmin_lib-install"										# LABADMIN INSTALL MODULE
	


#=== FUNCTION ==================================================================
#        NAME: help
# DESCRIPTION: Show help and exit
# PARAMETERS: 
#	$1	exit code
#===============================================================================
function help() {
	echo -e "Install and check labadmin dependencies for admin and host
  ADMIN INSTALL
   ${S_B}$(basename $0)${S_R} admin                                  Install admin controller

  HOSTS INSTALL
   ${S_B}$(basename $0)${S_R} host                                   Install and config hosts

  CHECK DEPENDENCIES
   ${S_B}$(basename $0)${S_R} admin -d ask|autoinstall|noinstall     No install, only check admin dependencies
   ${S_B}$(basename $0)${S_R} host  -d ask|autoinstall|noinstall     No install, only check host dependencies
"

	exit $1
}


#### CHECK PARAMETERS
[ $# -eq 0 ] && help
install_type="$1"
[[ "$install_type" != @(admin|host) ]] && labadmin_error "Incorrect install type parameter. Select admin or host installation" 1
shift

while getopts ":d:h" o
do
    case $o in
        d) # -d:dependencies
            dparam=1
            daction="$OPTARG"
            [[ "$daction" != @(ask|autoinstall|noinstall) ]] && labadmin_error "Incorrect check dependence action ${daction}\nSupported actions: ask, autoinstall and noinstall" 1            
            ;;
        h)
            help
            ;;
        *)
            labadmin_error "Error parameter" 1
            ;;
    esac
done


#### ACTION: INSTALL/CHECK
## DEPENDENCIES HOST
if [ "$install_type" = admin ] && [ "$dparam" ]; then
	load_scripts "$scripts_path"
    check_dependencies "$daction" "scripts_admindeps"
    echo

## DEPENDENCIES ADMIN
elif [ "$install_type" = host ] && [ "$dparam" ]; then
	load_scripts "$scripts_path"
    check_dependencies "$daction" "scripts_hostdeps" 
    echo

## INSTALL ADMIN
elif [ "$install_type" = admin ]; then
	load_scripts "$scripts_path"
    install_admin "$lab_id"

## INSTALL HOST
elif [ "$install_type" = host ]; then
	load_scripts "$scripts_path"
    install_host "$nhost" "$lab_id"

## OTHER CASE
else
    help 1
fi



