#!/usr/bin/env bash
#===================================================================================
# LABADMIN UNINSTALLER
#         FILE: uninstall
#
#  DESCRIPTION: Uninstall labadmin from host and admin
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#      VERSION: 2019.04
#      CREATED: 16.02.2017
#===================================================================================

#===============================================================================
#  LOAD LIBS
#===============================================================================
readonly labadmin_path="$(dirname $(readlink -f "${0}"))"                       # LABADMIN script root directory path
readonly lib_path="${labadmin_path}/lib/"                                       # LABADMIN LIB PATH
source "${lib_path}/labadmin_lib-admin"                                         # LABADMIN ADMIN VARIABLES AND FUNCTIONS
source "${lib_path}/labadmin_lib"												# LABADMIN GLOBAL VARIABLES AND FUNCTIONS
source "${lib_path}/labadmin_lib-install"										# LABADMIN INSTALL MODULE



#=== FUNCTION ==================================================================
#        NAME: help
# PARAMETER 1: exit code
# DESCRIPTION: Show help and exit
#===============================================================================
function help() {
	echo -e "Uninstall labadmin from host and admin
   ${S_B}$(basename $0)${S_R} admin            Uninstall admin
   ${S_B}$(basename $0)${S_R} host             Uninstall host
"
	exit $1
}



#=== FUNCTION ==================================================================
# NAME: uninstall_admin
# DESCRIPTION: uninstall labadmin from admin computer
# USAGE: uninstall_admin 
#===============================================================================
function uninstall_admin() {
	[ $EUID -ne 0 ] && labadmin_error "Install must be runed as root" 1

	labadmin_info "Removing directory $dir_install"
	rm -rf "$dir_install"

	labadmin_info "Removing /usr/bin links"
	rm -rf "/usr/bin/$(basename "$labadmin_file")"

	labadmin_info "Deactivate SUID for arp-scan command"
	chmod u-s "$(which arp-scan)"

	labadmin_info "Removing log files"
	rm -rf "$log_path"

	labadmin_info "Removing desktop files"
	rm /usr/share/applications/labadmin.desktop
	rm /usr/share/pixmaps/labadmin.png

	labadmin_info "Removing "$labadmin_group" group"
	delgroup "$labadmin_group"
}


#=== FUNCTION ==================================================================
# NAME: uninstall_host
# DESCRIPTION: uninstall labadmin from host computer
#===============================================================================
function uninstall_host() {
	[ $EUID -ne 0 ] && labadmin_error "Install must be runed as root" 1

	# Remove ssh authentication
	rm -v /root/.ssh/authorized_keys

	# Remove SSH server
	load_installer
	if [ "$?" -eq 0 ]; then
		installer_uninstall openssh-server
		rm -v /etc/ssh/sshd_config &>/dev/null
	else 
		labadmin_error "Unable to find uninstaller for openssh-server"
	fi
}



#### READ PARAMETERS
[ $# -ne 1 ] && help 1
case "$1" in
    admin)	uninstall_admin     ;;
    host) 	uninstall_host      ;;
    *) 		help 1				;;
esac
