#!/usr/bin/env bash
#===================================================================================
#     FILE: exam/end
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Come back host to normal config when exam ends"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="7za(p7zip-full|p7zip) setfacl(acl) xprintidle"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: poweroff after end
	read_param "$script_id" 1 "Poweroff host[Y/n]" "y"  "^(y|n)$"
    # PARAM2: remove user
    read_param "$script_id" 2 "Remove exam user [Y/n]" "y"  "^(y|n)$"
    # PARAM3: change pass	
    [ "${p2,,}" = "n" ] && read_param "$script_id" 3 "New user password (empty no change)" ""  ""
    return
fi


#=== EXEC SCRIPT ===================================================================
labadmin_cache_path="/home/.labadmin-cache/"					# Labadmin exam cache path
exam_end_script="${labadmin_cache_path}/current_exam-end.sh"	# Current exam end script
poweroff_end="$1"
remove_user="$2"
new_pass="$3"


### CHECK RECOVERY EXAM SCRIPT
[ ! -f "$exam_end_script" ] && labadmin_error "ERROR: no exam in progress (script $exam_end_script no exists)" 1

### EXEC EXAM RECOVERY SCRIPT
bash "$exam_end_script" "${remove_user}" "${new_pass}"; ec=$?
# Poweroff 
[ $ec -eq 0 ] && [ "${poweroff_end,,}" = "y" ] && { labadmin_info "\nNO ERRORS REPORTED -> POWEROFF"; poweroff&; }
exit $ec




