#!/usr/bin/env bash
#===================================================================================
#     FILE: file/dir
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(dirname $(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g'))"		# Directory: script directory with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Transfer files to/from host"
	script_type="menu"
	load_scriptinfo "$script_id" "$script_desc" "$script_type"
	return
fi
