#!/usr/bin/env bash
#===================================================================================
#     FILE: net/force-1000
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Force negotiated speed to gigabit"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="ethtool"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


#=== EXEC SCRIPT ===================================================================
iface_host="$(labadmin_iface "${labadmin_ipadmin}")"
ethtool -s "$iface_host" speed 1000 duplex full
