#!/usr/bin/env bash
#===================================================================================
#     FILE: software/vbox_extpack
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Update VirtualBox Extension Pack"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="vboxmanage"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: local path
	read_param "$script_id" 1 "Extension pack file (URL or remote path)" "" ""
	return
fi


#=== EXEC SCRIPT ===================================================================
ep_file="$1"	

# FILE ON URL (contains ://)
if [[ "$ep_file" == *://* ]]; then		
	t=$(mktemp -d)
	wget -P "$t" "$ep_file" || labadmin_error "Cant download file from $ep_file" 1
	[ $? -eq 0 ] && yes | vboxmanage extpack install --replace "$t"/*extpack 
	rm -rf "$t"

# FILE ON REMOTE PATH
else
	[ ! -r "$ep_file" ] && labadmin_error "Cant read file $ep_file" 1
	yes | vboxmanage extpack install --replace "$ep_file"
fi
