#!/usr/bin/env bash
#===================================================================================
#     FILE: clone/multicast/restore-part
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Restore remote partition from local partclone image using multicast"
	script_type="ssh+admin"
	script_bg="force win"
	script_admindeps="udp-sender(udpcast)"
	script_hostdeps="udp-receiver(udpcast) partclone.restore(partclone)"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM1: local path
	read_param "$script_id" 1 "Source local gzip image file" "" "."
	# PARAM2: remote dev
	read_param "$script_id" 2 "Remote destination partition file in /dev/ (sda1, sdb2,...)" "" "^[a-zA-Z0-9]+$"
	return
fi

#=== EXEC SCRIPT ===================================================================
src="$(eval echo "$1")"			# Resolve scape characteres like \ ,*, etc.
dest="/dev/${2}"


# REMOTE EXEC
if [ "${labadmin_script_type}" = "ssh" ]; then
	# CHECK DEST
	if [ ! -w "$dest" ]; then
		echo -e "\e[1m\e[91mCant write dev file "'"${dest}"'"\e[0m"
		return 1
	fi
	killall -9 udp-receiver 2>/dev/null
	udp-receiver --nokbd  | gzip -dc | partclone.restore -o "${dest}"

# LOCAL EXEC
elif [ "${labadmin_script_type}" = "admin" ]; then
	# CHECK SRC
	if [ ! -f "$src" ] || [ ! -r "$src" ]; then
		echo -e "\e[1m\e[91mCan't read local file $src\e[0m"
		return 1
	fi
	killall -9 udp-sender 2>/dev/null
	sleep 5
 	dd bs=1M if="$src" | udp-sender
fi
