#!/usr/bin/env bash
#===================================================================================
#     FILE: anydesk
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Start anydesk connection to remote host"
	script_type="ssh+admin"
	script_bg="sub"
	script_admindeps="anydesk(anydesk)"
	script_hostdeps="anydesk(anydesk)"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi

#=== EXEC SCRIPT ===================================================================

# REMOTE EXEC
if [ "${labadmin_script_type}" = "ssh" ]; then


# LOCAL EXEC
elif [ "${labadmin_script_type}" = "admin" ]; then

fi
