#!/usr/bin/env bash
#===================================================================================
#     FILE: anydesk
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Start anydesk connection to remote host"
	script_type="local"
	script_bg="force sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi

#=== EXEC SCRIPT ===================================================================

aid=$(labdmin_ssh_host_comm "${labadmin_nhost}" 'anydesk --get-id')
anydesk "$aid"
