#!/usr/bin/env bash
#===================================================================================
#     FILE: poweron
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path


#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Power ON host using network"
	script_type="inactive"
	script_bg="sub"
	script_admindeps="wakeonlan|wol"
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


#=== EXEC SCRIPT ===================================================================

# DEPENDENCIES
wol_command="$(labadmin_search_alternative wakeonlan wol)"

"$wol_command" "${labadmin_machost}"
