#!/usr/bin/env bash
#===================================================================================
#     FILE: hostname
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Set hostname"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: hostname
	read_param "$script_id" 1 'New hostname (use ${n} for replace for host number)' "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
n="${labadmin_nhost}"	# nhost
hn="$1"					# new hostname
hn="$(eval echo $hn)"	# eval replace ${n} for $n

echo '$cn = get-wmiobject win32_computersystem
$cn.rename("'"$hn"'")'
