#!/usr/bin/env bash
#===================================================================================
#     FILE: file/download
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Download URL resource in host Downloads folder"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM1: URL
	read_param "$script_id" 1 "URL" "" "."
	# PARAM2: remote path
	read_param "$script_id" 2 "Filename destination (default yyyy-mm-dd_hh-mm-ss_file.download)" "$(date +%Y-%m-%d_%H-%M-%S_file.download)" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
url="$1"
dest="$2"

echo 'Invoke-WebRequest -Uri "'"$url"'" -OutFile "'"$dest"'"'
