#!/usr/bin/env bash
#===================================================================================
# LABADMIN SCRIPT LIB
#         FILE: labadmin_lib-script
#  DESCRIPTION: labadmin lib for load and select scripts
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#	   LICENSE: GNU General Public License v3.0
#===================================================================================

#### EXTERNAL VARIABLES USED
# scripts_path
# shosts_listen
# ips[]
# log_path
# ipadmin
# labadmin_script
# labadmin_cmd
# cofig_id
# p0 p1 p2 p3 p4 p5 p6 p7 p8 p9
# p0param p1param p2param p3param p4param p5param p6param p7param p8param p9param

#### GLOBAL VARIABLES
declare -A scripts_desc					# Associative array indexed by script_id with scripts descriptions
declare -A scripts_type 				# Associative array indexed by script_id with scripts types
declare -A scripts_file 				# Associative array indexed by script_id with scripts file paths
declare -A scripts_bg 					# Associative array indexed by script_id with scripts background configs
declare -A scripts_parent				# Associative array indexed by script_id with scripts parent menu (if nested script)
declare -A scripts_admindeps			# Associative array indexed by script_id with admin dependencies
declare -A scripts_hostdeps				# Associative array indexed by script_id with host dependencies
unset script_id							# Current script id (name of file without extension) selected to exec
unset exec_bg							# Current background exec of selected script: sub|win|<empty>
unset hosts_err							# Array with host numbers with exit error exist status in current script
unset hosts_ok							# Array with host numbers with no exit error exist status in current script



#=== FUNCTION ==================================================================
# NAME: load_scripts
# DESCRIPTION: for info of each script file (desc, type, bg) in arrays
# PARAMETERS:
#	$1	path where search scripts recursvely or single file to load
#
# GLOBAL VARIABLES WRITTEN
#	scripts_desc[]
#	scripts_file[]
#   scripts_type[]
#	scripts_bg[]
#	scripts_parent[]
#===============================================================================
function load_scripts() {
	local search_path="$1"
	[ ${#scripts_file[*]} -gt 0 ] && return							# Exit if script was loaded previusly
	
	# DIRECTORY
	if [ -d  "$search_path" ]; then
		local IFS=$'\n\t'
		for s in $(find "$search_path" -type f); do
			source "$s" "--load-scriptinfo"
		done
	# FILE
	elif [ -f "$search_path" ]; then
		source "$search_path" "--load-scriptinfo"
	else
		labadmin_error "ERROR: can't load scripts from $search_path" 1
	fi
}



#=== FUNCTION ==================================================================
# NAME: load_scriptinfo
# DESCRIPTION: add script info in asociative scripts arrays.
# 	This function is called for each script for autoregister his information
#
# PARAMETERS
#	$1	script_id
#	$2	script_desc
#	$3	script_type
#	$4	script_bg
#	$5	admin-dependencies
#	$6	host-depedences
#
# GLOBAL VARIABLES WRITTEN
#	scripts_desc[]					Description of the script file
#	scripts_type[]					Type of the script file
#	scripts_bg[] 					Background config: deny, force sub, force win, sub, win or empty)
#	scripts_file[]					Path of the script file
#	scripts_parent[]				Scriptid of parent script menu (if a child script)
#	scripts_admindeps[]				List of admin dependencies
#	scripts_hostdeps[]				Lists of host dependencies
#===============================================================================
function load_scriptinfo() {
	local script_id="$1"
	local script_desc="$2"
	local script_type="$3"
	local script_bg="$4"
	local script_admindeps="$5"
	local script_hostdeps="$6"
	local script_file="${scripts_path}/${script_id}"
	local script_parent="${script_id%/*}"
	[ "${script_parent}" = "${script_id}" ] && script_parent=""

	# CHECK SCRIPT FILE
	[ ! -r "$script_file" ] && labadmin_error "Can't read script file $script_file" 1
	# CHECK SCRIPT TYPE
	[[ "${script_type}" != @(ssh|local|inactive|admin+local+admin|admin+local|local+admin|admin+ssh+admin|admin+ssh|ssh+admin|ssh+local|local+ssh|ssh&local|winrm-ps|winrm-cmd|menu) ]] && labadmin_error "${script_id}: unknown script type ${script_type}${S_R}" 1


	scripts_desc["$script_id"]="$script_desc"
	scripts_type["$script_id"]="$script_type"
	scripts_file["$script_id"]="$script_file"
	scripts_bg["$script_id"]="$script_bg"
	scripts_parent["$script_id"]="$script_parent"
	[ "$script_admindeps" ] && scripts_admindeps["$script_id"]="$script_admindeps"
	[ "$script_hostdeps" ] && scripts_hostdeps["$script_id"]="$script_hostdeps"
}




#=== FUNCTION ==================================================================
# NAME: select_script
# DESCRIPTION: 	shows script list (main scripts or submenu scripts) and ask for
#	script to exec.
#   The script is deal as parameter 0 (saved in p0 variable).
#
# PARAMETERS
#	$1		Current folder selected for script
#
# GLOBAL VARIALBES WRITTEN
#	script_id 		Script id selected
#	exec_bg			Type of background exec (sub, win or empty)
#===============================================================================
function select_script() {
	local script_current="$1"
	[ ! "$script_current" ] && unset exec_bg				# First call unset background config
	[ "$script_current" = "." ] && unset script_current		# Current dir . equal to empty

	# GENERATE MENU LIST
	local IFS=$'\n\t'
    local list="\n" listf listd
    local regex=""
	for f in $(ls "${scripts_path}/${script_current}/"); do
		[ "$f" = "dir" ] && continue
		s_id="${script_current:+${script_current}/}${f}"
		# If script is a menu (directory):
		if [ -d "${scripts_path}/${script_current}/${f}" ]; then
			listd="${listd:+${listd}\n}${f}/ ${scripts_desc[$s_id]}"
		# If script is a file
		else
			local script_desc="${scripts_desc[$s_id]}"
			[ "${dependence_errors[$s_id]}" ] && script_desc="${C_BR}${script_des} "'(!)'"${S_R}"	# Mark scripts with missing dependencies 
			listf="${listf:+${listf}\n}${f} ${alert_dependence_start}${script_desc}${alert_dependence_end}"
		fi
	done
	list="\n${listd}\n${listf}"	# Sort directories first and files after

	unset script_id
	while [ ! "$script_id" ]; do
		# READ SCRIPT AS PARAM
		local help="${S_D}Action options${S_R}
 ${C_Y}action${S_R}                   Exec action
 ${C_LY}action${S_R} &                 Exec action in background (all in this panel)
 ${C_LY}action${S_R} &&                Exec action in background (in separate panles)
 ${C_LB}dir${S_R}                      Enter to dir menu     
 cd ..                    Up to parent menu
 ${C_N}${S_U}d${S_R}ir                      List scripts of current menu

${S_D}Internal commands${S_R}
 ${C_N}${S_U}n${S_R}ew-panel                Open extra script panel
 ${C_N}${S_U}c${S_R}lose-panel              Close current script panel
 ${C_N}${S_U}r${S_R}efresh-map              Refresh map with current selection
 ${C_N}${S_U}s${S_R}elect-hosts <range>     Select new host range
 ${C_N}${S_U}l${S_R}ist-hosts               List current selected hosts
 l${C_N}${S_U}a${S_R}b <lab>                Change lab
 ${C_N}${S_U}m${S_R}ode lin|win             Set hosts OS: linux or windows
 ${C_N}${S_U}e${S_R}xit                     Exit labadmin session"
		regex=".*"
		cd "${labadmin_tmp_path}/actions/$srvmode/${script_current}"
		read_param "${script_current:-/}" "0" "$list" "" "$regex" "$help"

		# P0: remove starting cd
		p0="$(echo "$p0" | sed 's/^cd *//')"
		# SCRIPT_ID: curret path + p0 removing final space or /
		script_id="$(echo "${script_current:+${script_current}/}${p0}" | sed "s/[/ ]$//")"

		# ACTION EMPTY: show prompt again
		if [ ! "$p0" ]; then
			unset script_id
			list="Action"
			continue

		# ACTION n: new extra script panel
		elif [[ "${p0,,}" = @(n?( )|new-panel?( )) ]]; then
			tmux_create-window-com "SP$(($(tmux_list-windows | egrep "^SP[0-9]+$" | tail -1 | egrep -o "[0-9]+")+1))" "${labadmin_path}/bin/labadmin-tui-script ${labadmin_PID}" "focus"
			return 1

		# ACTION c: close extra script panel
		elif [[ "${p0,,}" = @(c?( )|close-panel?( )) ]]; then
			tmux_close-windows
			return 1			

		# ACTION r: refresh map panel
		elif [[ "${p0,,}" = @(r?( )|refresh-map?( )) ]]; then
			[ ! "$map_PID" ] && labadmin_tmp-vars-load map_PID
			kill -35 "$map_PID"
			unset script_id; list="Action"; continue			

		# ACTION s: select range in map panel
		elif [[ "${p0,,}" = @(s *|select-hosts *) ]]; then
			[ ! "$map_PID" ] && labadmin_tmp-vars-load map_PID
			rhosts=$(echo "$p0" | cut -f2- -d" "); labadmin_tmp-vars-save rhosts
			kill -36 "$map_PID"
			unset script_id; list="Action"; continue	

		# ACTION l: list selected hosts
		elif [[ "${p0,,}" = @(l?( )|list-hosts?( )) ]]; then
			labadmin_tmp-vars-load shosts_listen
			echo -e "    ${S_B}HOSTS${S_R}($(echo "$shosts_listen" | wc -w)): $(echo "$shosts_listen" | xargs)\n"
			unset script_id; list="Action"; continue

		# ACTION a: show labs
		elif [[ "${p0,,}" = @(a?( )|lab?( )) ]]; then
			l=$(ls "${labs_path}" | tr "\n" " ")
			echo -e "    ${S_B}LABS${S_R}($(echo "$l" | wc -w)): ${l}\n"
			unset script_id; list="Action"; continue	

		# ACTION a: change lab
		elif [[ "${p0,,}" = @(a *|lab *) ]]; then
			l=$(echo "$p0" | cut -f2- -d" " | xargs); lf="${labs_path}/${l}"			
			# lab not found
			[ ! -r "$lf" ] && { labadmin_error "    Lab $l not found"; echo -e "    LABS: $(ls "${labs_path}" | tr "\n" " " | sed 's/ask//')\n"; unset script_id; list="Action"; continue; }
			# lab is current lab
			[ "$l" = "$lab_id" ] && { unset script_id; list="Action"; continue; }

			[ ! "$map_PID" ] && labadmin_tmp-vars-load map_PID
			lab_file="$lf"; lab_id="$l"; rhosts=""; labadmin_tmp-vars-save lab_file lab_id rhosts
			kill -37 "$map_PID"
			labadmin_status-send "\n ${C_N}###${S_R} ${S_B}MAP SELECTED: ${C_Y}${l}${S_R}"
			clear; exec bash "$0" $labadmin_PID		

		# ACTION m: change srvmode
		elif [[ "${p0,,}" = @(m *|mode *) ]]; then
			m=$(echo "$p0" | cut -f2- -d" " | xargs); [ "${m,,}" = win ] && m="winrm"; [[ "${m,,}" == @(lin|linux) ]] && m="ssh"; 
			[[ "$m" != @(ssh|winrm) ]] && { labadmin_error "    Incorrect mode $m"; unset script_id; list="Action"; continue; }
			# mode is current mode
			[ "$m" = "$srvmode" ] && { unset script_id; list="Action"; continue; }

			[ ! "$map_PID" ] && labadmin_tmp-vars-load map_PID
			srvmode="$m"; rhosts=""; labadmin_tmp-vars-save srvmode rhosts
			kill -38 "$map_PID" && clear

			labadmin_status-send "\n ${C_N}##${S_R} SRV MODE SELECTED: ${C_Y}${m^^}${S_R}"
			clear; exec bash "$0" $labadmin_PID

		# ACTION exit|quit: exit script
		elif [[ "${p0,,}" == @(e?( )|exit?( )|quit?( )) ]]; then
			labadmin_exit

		# ACTION LIST: list menu script again
		elif [[ "${p0}" = @(d|dir|ls) ]]; then
			select_script "$script_current"
			return

		# ACTION PARENT
		elif [ "${p0}" = ".." ]; then
			if [ ! "$script_current" ]; then
				select_script "$script_current"
			else
				select_script "$(dirname "$script_current")"
			fi
			return
		fi


		# Check if action in background win (&&)
		if [ "${script_id: -2}" = "&&" ]; then
			script_id="$(echo ${script_id:0: -2} | xargs)"		# Remove final & and trim spaces
			exec_bg="win"
		# Check if action in background sub (&)
		elif [ "${script_id: -1}" = "&" ]; then
			script_id="$(echo ${script_id:0: -1} | xargs)"		# Remove final & and trim spaces
			exec_bg="sub"
		fi

		# Check script_bg force
		[[ "${scripts_bg[$script_id]}" == *force* ]] && exec_bg="$(echo "${scripts_bg[$script_id]}" | sed 's/[^[:alpha:]]*force[^[:alpha:]]*//g')"

		# ACTION: if script not exists show error and list menu again
		if [ ! "${scripts_file[$script_id]}" ]; then
			labadmin_error "    ! Script ${script_id} not found"
			unset script_id
			list="Action"
			continue
		fi

		# Check script_bg deny
		if [ "$exec_bg" ] && [ "${scripts_bg[$script_id]}" = "deny" ]; then
			labadmin_error "   Action ${script_id} can't be runned in background\n"
			unset script_id exec_bg
			continue
		fi

		# DIRECTORY SELECTED: continue next selection
		if [ -d "${scripts_path}/${script_id}/" ]; then
			select_script "$script_id"
			return
		fi
	done

	# If found dependence errors in selected script show warning
	[ "${dependence_errors[$script_id]}" ] && labadmin_error "    WARNING: Selected script has missing dependencies: ${dependence_errors[$script_id]}"
	# Prevent recursive loop when call another instance of labadmin

	return 0
}




#=== FUNCTION ==================================================================
# NAME: read_params
# DESCRIPTION: read script params calling read_param function (on the script) and
# 	if current action is a menu script show subscripts list and read script for
#	exec and params
#
# GLOBAL VARIABLES WRITTEN
#	script_id
#===============================================================================
function read_params() {
	reading_params=1

	# Reset params
	[ ! "$p1param" ] && unset p1
	[ ! "$p2param" ] && unset p2
	[ ! "$p3param" ] && unset p3
	[ ! "$p4param" ] && unset p4
	[ ! "$p5param" ] && unset p5
	[ ! "$p6param" ] && unset p6
	[ ! "$p7param" ] && unset p7
	[ ! "$p8param" ] && unset p8
	[ ! "$p9param" ] && unset p9

	# READ SCRIPT PARAMS
	source "${scripts_file["$script_id"]}" --readparams

	unset reading_params
}



#=== FUNCTION ==================================================================
# NAME: show_menulist()
# DESCRIPTION: Show a menu list formatted in two columns
# PARAMETERS
#   $1  Text with menu in two columns
#===============================================================================
function show_menulist() {
    local text="$(echo -e "$1")"
    local left_margin="  "        # Space at left of each lines
    local col_width=16            # With of first column
    local IFS=$'\n'
    local menu=""
    for l in $text; do
        local opt="$(echo "$l" | awk '{print $1}')"
		[ ! "$opt" ] && { menu="${menu}\n"; continue; }
		local desc="$(echo "$l" | awk '{$1=""; print $0}')"
        local space=$((${col_width}-${#opt}))
		if [ "${opt: -1}" = "/" ]; then opt="[${C_LB}${opt}${C_D}]"
		else opt="[${C_LY}${opt}${C_D}]"; fi
        menu="${menu:+${menu}\n}${left_margin}${opt}$(seq -s" " "$space" | tr -d "[0-9]")${desc}"
    done
    echo -e "$menu"
}




#=== FUNCTION ==================================================================
# NAME: read_param
# DESCRIPTION: ask user for a parameter and save it in $pX variable (X=1,2,3...)
#	If param was fixed in command line only show it
#	Checks param format with regex
# PARAMETERS
#   $1	Script ID
#	$2	Parameter number
#   $3	Parameter description to show in read (if multiple lines show menu selection)
#	$4	Default parameter value
#   $5	Regular expresión for check param
#   $6  Parameter help
#
# GLOBAL VARIABLES WRITTEN
#	p0	parameter 0
#	p1	parameter 1
#	p2	parameter 2
#	p3	parameter 3
# 	p4	parameter 4
#	p5	parameter 5
# 	p6	parameter 6
#	p7	parameter 7
#	p8	parameter 8
#	p9	parameter 9
#===============================================================================
function read_param() {
	local script_id="$1"
	local np="$2"
	local desc="$3"
	local default="$4"
	local regexp="$5"
	local help="$6"

	# Param desc multiline: show as menu list
	if [ "$(echo -e "$desc" | wc -l)" -gt 1 ]; then
		if ! eval [ "\$p${np}param" ]; then 	# No fixed param from command line
			show_menulist "$desc"
			echo
		fi
		desc="Action"
	fi

	local vp cursor_col
	while true; do
        if ! eval [ "\$p${np}param" ]; then   				# No fixed param from command line
			### COMPOSE PROMPT
			# If script_id is a file in / -> color yellow
			local scriptid_color="${C_LY}$script_id${C_D}"
			# If script_id is a menu -> color blue
			if [ "${scripts_type["$script_id"]}" = "menu" ] || [ "$script_id" = "/" ]; then scriptid_color="${C_LB}$script_id${C_D}"
			# If script_id is a file inside a directory -> dir in blue and file in yellow
			elif [ "${script_id#*/}" != "$script_id" ]; then scriptid_color="${C_LB}$(dirname "$script_id")/${C_LY}$(basename "$script_id")${C_D}"; fi
			local ps_read="  > [${scriptid_color}$([ "$exec_bg" ]&&echo "&")] ${S_U}${desc}${S_R}:"
			ps_read="$(echo -e "$ps_read")"

			# Read param from keyboard
            read -r -e -p "$(echo -en "$ps_read") " p				# read -e allow TAB completion, read -r avoid delete \x in special chars
            eval "p${np}"=\""$p"\"
        fi
        eval vp="\$p${np}"

        # Default value if parameter is empty
        if [ ! "$vp" ] && [ "$default" ]; then
        	eval p${np}=\""$default"\"
        	vp="$default"
        	cursor_move-up 1
			cursor_col=$(echo -e "$ps_read"| tail -1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | wc -m)  # sed remove colors and wc count horizontal space
			cursor_move-right "$((cursor_col))"
        	echo "$default"
        fi

        # Help
        if [[ "$vp" == @(h|help) ]]; then
            if [ "$help" ]; then
            	labadmin_draw-box 0 4 "$help" "${desc/(*)/}"
            else
            	echo -e "    ${C_N}No help for this parameter${S_R}\n"
            fi
            continue
        fi

        # Format check
        if [ "$regexp" ] && ! echo "$vp" | grep -Ei "$regexp"&>/dev/null; then
            echo -e "    ${C_LR}! Format error${S_R}. Accepted: $regexp"
			echo
            eval [ \$p${np}param ] && unset p${np}param
            continue
        fi
        return
    done
}





#=== FUNCTION ==================================================================
# NAME: exec_script
# DESCRIPTION: exec current script $script_id located in $scripts_path in local 
#              or remote
# PARAMETERS
#	$1	nhost 		host number where exec the script (empty if admin)
#
# GLOBAL VARIALBES WRITTEN
#   hosts_ok[]		host with exit code 0 when execution ends
#   hosts_err[]		host with exit code !=0 when execution ends
#===============================================================================
function exec_script() {
	local nhost="$1"
	local iphost=${ips["$nhost"]}   
	local script_file="${scripts_file[$script_id]}"
	local script_type="${scripts_type[$script_id]}"

	# SHOW HEADER
	echo -e "\n┌─── ${S_B}[${nhost:-ADMIN}] ${C_LB}${iphost:-LOCALHOST}${C_D} → EXEC $script_id${S_R} $(seq -s"─" $((${COLUMNS}-17-${#nhost}-${#iphost}-${#script_id}$([ ! "$nhost" ] && echo "-5")$([ ! "$iphost" ] && echo "-9")))| tr -d "[0-9]")┐"

	#### EXEC BACKGROUND START (prepare output)
	[ "$exec_bg" = "sub" ] && stdout_nhost start "$nhost"	

	#### EXEC WIN
	if [ "$exec_bg" = "win" ]; then
		labadmin_tmp-vars-save-1file execbg-win winrmpass script_id p0 p1 p2 p3 p4 p5 p6 p7 p8 p9
		exec_script_win "$nhost"
		return $?
	#### EXEC LOCAL
	elif [ ! "$nhost" ] || [[ "${script_type,,}" = @(local|inactive|admin+local+admin|admin+local|local+admin) ]]; then
		exec_script_local "$nhost"
		out=$?
	#### EXEC SSH AND THEN LOCAL
	elif [ "$script_type" = "ssh+local" ]; then
		exec_script_ssh "$nhost"
		out=$?		
		if [ "$out" = 0 ]; then
			exec_script_local "$nhost"
			out=$?
		fi
	#### EXEC LOCAL AND THEN SSH
	elif [ "$script_type" = "local+ssh" ]; then
		exec_script_local "$nhost"
		out=$?		
		if [ "$out" = 0 ]; then
			exec_script_ssh "$nhost"
			out=$?
		fi	
	#### EXEC SSH AND LOCAL SIMULTANEOUSLY
	elif [ "$script_type" = "ssh&local" ]; then
		exec_script_ssh "$nhost" &
		exec_script_local "$nhost"
		out=$?		
	#### EXEC SSH
	elif [ "$nhost" ] && [[ "${script_type,,}" = @(ssh|admin+ssh+admin|admin+ssh|ssh+admin) ]] ; then
		exec_script_ssh "$nhost"
		out=$?		
	#### EXEC REMOTE WINRM-PS
	elif [ "$script_type" = "winrm-ps" ]; then
		exec_script_winrm-ps "$nhost"
		out=$?
	#### EXEC REMOTE WINRM-cmd
	elif [ "$script_type" = "winrm-cmd" ]; then
		exec_script_winrm-cmd "$nhost"
		out=$?
	else
		labadmin_error "Incorrect script type $script_type for $script_file" 
		out=1
	fi

	#### EXEC BACKGROUND END (restore output)
	[ "$exec_bg" = "sub" ] && stdout_nhost end "$nhost"
	
	# EXIT CODE AND FOOTER
	if [ "$out" -ne 0 ]; then
		[ "$exec_bg" = "sub" ] && labadmin_beep "error1"
		[ "$nhost" ] && hosts_err[$nhost]=$out  
		echo -e "${S_R}└─── ${S_B}[${nhost:-ADMIN}] ${C_LB}${iphost:-LOCALHOST}${C_D} ← ${C_LR}ERROR ($out)${C_D}${S_R} $(seq -s"─" $((${COLUMNS}-21-${#nhost}-${#iphost}-${#out}$([ ! "$nhost" ] && echo "-5")$([ ! "$iphost" ] && echo "-9")))| tr -d "[0-9]")─┘"
		[ "$tmuxmode" ] && labadmin_status-send "  [${nhost:-AD}] ${S_B}${C_Y}${script_id} ${C_R}EXEC ERROR${S_R}"
	else
		[ "$nhost" ] && hosts_ok[$nhost]=$out  
		echo -e "${S_R}└─── ${S_B}[${nhost:-ADMIN}] ${C_LB}${iphost:-LOCALHOST}${C_D} ← ${C_LG}OK${C_D}${S_R} $(seq -s"─" $((${COLUMNS}-15-${#nhost}-${#iphost}$([ ! "$nhost" ] && echo "-5")$([ ! "$iphost" ] && echo "-9")))| tr -d "[0-9]")─┘"
		[ "$tmuxmode" ] && labadmin_status-send "  [${nhost:-AD}] ${S_B}${C_Y}${script_id} ${C_G}EXEC OK${S_R}"
	fi

	return $out
}


#=== FUNCTION ==================================================================
# NAME: labadmin_export_vars_code
# DESCRIPTION: for each variable name to export when exec script show
#              labadmin_<variable_name>=<variable_value> 
#
#              Variables exported are:
#                labadmin_iface
#                labadmin_sshuser
#                labadmin_sshport
#                labadmin_ipadmin
#                labadmin_iphost
#                labadmin_nhost
#                labadmin_script_type
#                labadmin_winrmuser
#                labadmin_winrmport
#				 labadmin_shosts_listen
#                labadmin_machost
#				 labadmin_script_type_state
#
#===============================================================================
function labadmin_export_vars_code() {
	vars_export="iface sshuser sshport ipadmin iphost nhost script_type winrmuser winrmport shosts_listen script_type_state"

    for vn in $vars_export; do
        echo "labadmin_${vn}=\"${!vn}\""
    done

    echo "labadmin_machost=\"${macs[$nhost]}\""
}


#=== FUNCTION ==================================================================
# NAME: exec_script_win
# DESCRIPTION: exec current $script_id in a new tmux window
#
# PARAMETERS
#	$1	nhost where exec the script
#===============================================================================
function exec_script_win() {
	local nhost="$1"
	local com="${labadmin_path}/bin/labadmin-tui-scriptwin ${labadmin_PID} ${nhost}"
	labadmin_info "Opening tmux window $nhost"
	tmux_create-window-com "$nhost" "$com"
}


#=== FUNCTION ==================================================================
# NAME: exec_script_ssh
# DESCRIPTION: exec current $script_id script in remote host using SSH
#              lib/labdamin_global and labadmin_export_vars_code is 
#              exec before the script code
#
# PARAMETERS
#	$1	nhost where exec the script
#===============================================================================
function exec_script_ssh() {
	local nhost="$1"
	local iphost=${ips[$nhost]}
	local script_file="${scripts_file[$script_id]}"

	( 
		cat "${lib_path}/labadmin_lib" 
		script_type="ssh" labadmin_export_vars_code
		cat "$script_file" 
	) | ssh -T $sshuser@$iphost -p $sshport -oStrictHostKeyChecking=no 'cat | bash /dev/stdin' "'""$p1""'" "'""$p2""'" "'""$p3""'" "'""$p4""'" "'""$p5""'" "'""$p6""'" "'""$p7""'" "'""$p8""'" "'""$p9""'"
	
	return $?
}


#=== FUNCTION ==================================================================
# NAME: exec_script_local
# DESCRIPTION: exec current $script_id script in local  
#              lib/labdamin_global and labadmin_export_vars_code is 
#              exec before the script code
#
# PARAMETERS
#	$1	nhost where exec the script. If empty exec in admin mode
#===============================================================================
function exec_script_local() {
	local nhost="$1"
	local iphost=${ips["$nhost"]}
	local script_type="local"; 	[ ! "$nhost" ] && script_type="admin"
	local script_file="${scripts_file[$script_id]}"

	(
		source "${lib_path}/labadmin_lib"
		eval $(script_type="$script_type" labadmin_export_vars_code)
		source "$script_file" "$p1" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8" "$p9" 	
	)

	return $?
}

#=== FUNCTION ==================================================================
# NAME: exec_script_winrm-ps
# DESCRIPTION: exec current $script_id script in remote host using WINRM Powershell
#              lib/labdamin_global and labadmin_export_vars_code is 
#              exec before the script code
#
# PARAMETERS
#	$1	nhost where exec the script
#===============================================================================
function exec_script_winrm-ps() {
	local nhost="$1"
	local iphost=${ips[$nhost]}
	local script_file="${scripts_file[$script_id]}"

	ps_script=$(
		source "${lib_path}/labadmin_lib"
		eval $(script_type="winrm-ps" labadmin_export_vars_code)	
		source "$script_file" "$p1" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8" "$p9"
	)
	echo -en "${C_LB}"; echo -n "$ps_script"; echo -e "${C_D}"
	ps_script_line="$(echo "$ps_script" | sed -z 's/\n/; /g' | sed 's/"/\\"/g')"
	"${bin_path}/winrm-go" -hostname "$iphost" -username "$winrmuser" -password "$winrmpass" 'powershell -command "&{'"$ps_script_line"'}"'	
	return $?
}

#=== FUNCTION ==================================================================
# NAME: exec_script_winrm-cmd
# DESCRIPTION: exec current $script_id script in remote host using WINRM CMD
#              lib/labdamin_global and labadmin_export_vars_code is 
#              exec before the script code
#
# PARAMETERS
#	$1	nhost where exec the script
#===============================================================================
function exec_script_winrm-cmd() {
	local nhost="$1"
	local iphost=${ips[$nhost]}
	local script_file="${scripts_file[$script_id]}"

	ps_script=$(
		source "${lib_path}/labadmin_lib"
		eval $(script_type="winrm-cmd" labadmin_export_vars_code)
		source "$script_file" "$p1" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8" "$p9"
	)
	echo -en "${C_LB}"; echo -n "$ps_script"; echo -e "${C_D}"
	ps_script_line="$(echo "$ps_script" | sed -z 's/\n/ & /g' | sed 's/"/\\"/g')"
	"${bin_path}/winrm-go" -hostname "$iphost" -username "$winrmuser" -password "$winrmpass" "$ps_script_line"
	return $?
}




#=== FUNCTION ==================================================================
# NAME: stdout_nhost
# DESCRIPTION: config outout format to:
#	- Addding host number colored at starting each line (red background in stderr)
#
# PARAMETERS
#	$1: start/end
#	$2: nhost
#===============================================================================
function stdout_nhost() {
	case "$1" in
	start)
		local random_color=$((3+$RANDOM%2*6))$((2+$RANDOM%5))		# Color number: [3,9][2-6]
		#STDERR
		exec 9>&2
		exec 8> >(
		    while IFS='' read -r line || [ -n "$line" ]; do
		       echo -en "  ${S_R}\e[${random_color}m\e[41m[$2]${S_R}  "
			   echo "${line}"
		    done
		)
		#STDOUT
		exec 7>&1
		exec 6> >(
		    while IFS='' read -r line || [ -n "$line" ]; do
		       echo -en "  ${S_R}\e[${random_color}m[$2]${S_R}  "
			   echo "${line}"
		    done
		)
		exec 2>&8; exec 1>&6;
	;;
	end)
		exec 2>&9
		exec 1>&7
	;;
	esac
}
