#!/usr/bin/env bash                                                                                                                                                                                                 
#===================================================================================
#     FILE: screen/grid
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"     # Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
    script_desc="Show screenshots for selected host in a grid view"
    script_type="local+admin"
    script_bg="force sub"
    script_admindeps=""
    script_hostdeps="import(imagemagick)"
    load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
    return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM1: delay
    read_param "$script_id" 1 "Delay seconds (default 5)"  "5" "^[1-9]([0-9])*$"
    # PARAM2: image quality
    read_param "$script_id" 2 "Image quality (default 10, range 10-100)"  "10" "^[1-9]([0-9])*$"
	return
fi


#=== EXEC SCRIPT ===================================================================

# LOCAL EXEC
if [ "${labadmin_script_type}" = "local" ]; then
    dsec="$1"
	iq="$2"
    
	sleep 2
	dir_dest=$(ls -dt "${labadmin_tmp_path}/screenshot-grid."* | head -1)
	[ ! -w "$dir_dest" ] && labadmin_error "Can't write in directory $dir_dest" 1
	[ "$iq" -lt 10 ] && iq=10; [ "$iq" -gt 100 ] && iq=100

    while [ ! -f "$dir_dest/stop" ]; do
        file_tmp="$dir_dest/${labadmin_nhost}.jpg"
        echo -e " ${S_B}${file_tmp}${S_R}"
        labdmin_ssh_host_comm "${labadmin_nhost}" '
u=($(labadmin_users-display | head -1))
[ ! "${u[0]}" ] && labadmin_error "No users logged" 1
modprobe -r pcspkr
su -l "${u[0]}" -c "import -window root -display "${u[1]}" -quality '${iq}' -interlace Plane jpg:-"' > "${file_tmp}"

        sleep $dsec
    done

# ADMIN EXEC
elif [ "${labadmin_script_type}" = "admin" ]; then
    dsec="$1"
    dir_dest=$(mktemp -d "${labadmin_tmp_path}/screenshot-grid.XXXXXXXX")
    [ ! -w "$dir_dest" ] && labadmin_error "Can't write in directory $dir_dest" 1 

	labadmin_info-list "Saving screenshots in: ${S_B}$dir_dest${S_R}"

	screenshot_grid_url="file://${labadmin_path}/screenshot-grid/screenshot-grid.html?lab=$(echo -n "$labname" | base64 -w0)&dir=$(echo -n "$dir_dest" | base64 -w0)&map=$( echo -n "$map" | base64 -w0)&ref=${dsec}"
	labadmin_info-list "Opening Labadmin Screenshot Grid: ${S_B}$screenshot_grid_url${S_R}"
	x-www-browser "${screenshot_grid_url}" &>/dev/null &

    labadmin_info-list "Press ${S_B}[ENTER]${S_R} to ${S_B}stop${S_R} saving screenshots\n"
	read
    touch "$dir_dest/stop"
    ( sleep 10; rm "$dir_dest/stop" &>/dev/null)& 
fi
