#!/usr/bin/env bash
#===================================================================================
#     FILE: dfc/rt
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Reboot system in unfrozen state (permanent)"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return
#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: pass
    read_param "$script_id" 1 "DF password" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
pass="$1"
echo 'DFC.exe '"${pass}"' /THAWNEXTBOOT
if ($lastExitCode -eq 0) { Restart-Computer -Force
} else { echo "ERROR: $lastExitCode" }'
