#!/usr/bin/env bash
#===================================================================================
#     FILE: clone/gpt-table/save-table
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Backup remote partition table and save in local path"
    script_type="local"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="dd"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: remote dev
	read_param "$script_id" 1 "Source remote disk file in /dev/ (sda, sdb,...)" "" "^[a-zA-Z]+$"
	read_param "$script_id" 2 "Local path to save (directory)" "" "."
	return
fi

#=== EXEC SCRIPT ===================================================================
src="/dev/${1}"
dest="$(eval echo "$2")"			# Resolve scape characteres like \ ,*, etc.

# CHECK DEST
[ ! -w "$dest" ] || [ ! -d "$dest" ] && labadmin_error "Can't write in local directory $dest" 1

# CHECK SRC
labdmin_ssh_host_comm "${labadmin_nhost}" '
src="$(eval echo "'"$src"'")"				 # Resolve scape characteres like \ ,*, etc.
[ ! -r "$src" ] && labadmin_error "Cant locate dev file "${src}" 1
exit 0
'
[ $? -ne 0 ] && exit 1

# SAVE TABLE
labdmin_ssh_host_comm "${labadmin_nhost}" 'dd if="'"${src}"'" bs=512 count='"${last}" > "${dest}/$(date +%Y-%m-%d)_$(basename "$src").${last}"
