#!/usr/bin/env bash
#===================================================================================
#     FILE: conf/sudoers/remove
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Remove line from sudoers file"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="visudo"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	read_param "$script_id" 1 "User (or %group, default all lines)"  "" ""
	read_param "$script_id" 2 "Filter to remove lines"  "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
user="$1"
filter="$2"

[ ! -f /etc/sudoers ] && labadmin_error "Cant find file /etc/sudoers"

sed -i "/^${user}.*${cmd}$/d" /etc/sudoers | EDITOR='tee' visudo
