#!/usr/bin/env bash
#===================================================================================
#     FILE: user/pass
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Set user password"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="passwd"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: user
	read_param "$script_id" 1 "User" "" "."
	# PARAM2: password
	read_param "$script_id" 2 "Password" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
user="$1"
pass="$2"

# Set password
passwd "$user" <<EOF
$pass
$pass
EOF
