#!/usr/bin/env bash
#===================================================================================
#     FILE: user/unlock
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Unlock users"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="passwd"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: users
	read_param "$script_id" 1 "Users (space separated, default all users)"
	return
fi


#=== EXEC SCRIPT ===================================================================
user="$2"

[ ! "$user" ] && user=$(ls /home)
[ ! "$user" ] && labadmin_error "No users selected" 1


for u in $user; do
	! id "$u" &>/dev/null && continue
	[ "$u" = root ] && continue		# Prevent lock root
	passwd -u "$u"					# unlock user
done
