#!/usr/bin/env bash
#===================================================================================
#     FILE: user/pass
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Set user password"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM1: username
	read_param "$script_id" 1 "Username" "" "."
	# PARAM2: password
    read_param "$script_id" 2 "Password" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
user="$1"
pass="$2"

echo 'Get-LocalUser -Name "'"$user"'" | Set-LocalUser -Password (ConvertTo-SecureString "'"$pass"'" -AsPlainText -Force)'
