#!/usr/bin/env bash
#===================================================================================
#     FILE: clone/mbr-table/del-part
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Delete partition"
    script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="fdisk"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1
	read_param "$script_id" 1 "Remote disk file in /dev/ (sda, sdb,...)" "" "^[a-zA-Z]+$"
	# PARAM2
	read_param "$script_id" 2 "Partition number" "" "^[0-9]+$"
	return
fi

#=== EXEC SCRIPT ===================================================================
dev="/dev/${1}"
pn="${2}"

[ ! -r "${dev}" ] && labadmin_error "Cant locate dev file ${dev}" 1


# DELETE PARTITION
echo -e "d\n${pn}\nw" | fdisk "$dev"
fdisk -l "$dev"
