#!/usr/bin/env bash
#===================================================================================
#        FILE: ask
# DESCRIPTION: Meta config file for ask user waht config file use
#      AUTHOR: Leonardo Marco
#     LICENSE: GNU General Public License v3.0
#=============================================================================


[ ! -d "$configs_path" ] && labadmin_error "Can't access config path $configs_path" 1

(
IFS=$'\n\t'
for i in $(find "$configs_path" -type f); do
	i="$(echo "$i" | sed 's\'"${configs_path}"'\\g')"		# Strip $configs_path from files
	[[ "$i" == @(ask|default) ]] && continue
	echo -e "    [${C_LY}${i}${C_D}]\t$(grep "^labname=" "${configs_path}/$i"| cut -f2 -d= | tr -d \")"
done
)

echo

unset config_file
while [ ! -r "$config_file" ] || [ ! -f "$config_file" ]; do
	echo -en "  > ${S_U}Select config file${S_R}:"
	read -e -p " " config_id
	[ ! "$config_id" ] && continue

	config_file="$configs_path/${config_id}"
	([ ! -r "$config_file" ] || [ ! -f "$config_file" ]) && labadmin_error "  ! Can't access config file $(echo "$config_file" | tr -s "/")"
done

echo
source "$config_file"	# Import variables from config file



