#!/usr/bin/env bash
#===================================================================================
#     FILE: virtualbox/bridge/enable
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Enable bridged network for all users"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: persistent?
	read_param "$script_id" 2 "Persistent [Y/n]" "y" "^(y|n)$"
	return
fi


#=== EXEC SCRIPT ===================================================================
persis="$1"

# CHECK VIRTUALBOX INSTALLED
! which virtualbox &>/dev/null && labadmin_error "Virtualbox not installed" 1

[ "${persis,,}" = "y" ] && rm -v /etc/modprobe.d/labadmin-vboxnetflt.conf
modprobe vboxnetflt
