#!/usr/bin/env bash
#===================================================================================
#     FILE: virtualbox/bridge/status
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Show status of bridged network for all users"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


#=== EXEC SCRIPT ===================================================================

# CHECK VIRTUALBOX INSTALLED
! which virtualbox &>/dev/null && labadmin_error "Virtualbox not installed" 1

if lsmod | grep -q "^vboxnetflt\b"; then
	echo -e " -Bridged network: ${C_BR}ENABLED${S_R}"
else
	echo -e " -Bridged network: ${C_BG}DISABLED${S_R}"
fi
if grep vboxnetflt /etc/modprobe.d/labadmin-vboxnetflt.conf &>/dev/null; then
	echo -e " -Persistence:     ${C_BG}DISABLED${S_R}"
else
	echo -e " -Persistence:     ${C_BR}ENABLED${S_R}"
fi

