#!/usr/bin/env bash
#===================================================================================
#     FILE: process/term
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Term all process of logged users"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


#=== EXEC SCRIPT ===================================================================

# Get logged users
users="$(who | awk '{print $1}')"
[ ! "$users" ] && labadmin_error "Nobody are logged" 1


for u in $users; do
	[ "$u" = root ] && continue			# Prevent term root
	echo -e "${C_LY}USER $u${C_D}"
	pkill -TERM -u "$u"
done
