#!/usr/bin/env bash
#===================================================================================
#     FILE: net/iptables/blacklist
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD SCRIPT INFO ==============================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Start blacklist (delete all rules and allow all ips but exceptions)"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="iptables"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: persistent?
	read_param "$script_id" 1 "Persistent [Y/n]" "y" "^(y|n)$"
	return
fi


#=== EXEC SCRIPT ===================================================================
per="$1"

iptables -F

# ACCEPT all connections for LABADMIN port
iptables -I INPUT -p tcp  --dport "${labadmin_sshport}" -j ACCEPT
iptables -I OUTPUT -p tcp  --sport "${labadmin_sshport}" -j ACCEPT	

iptables -L --line-numbers

if [ "${per,,}" = "y" ]; then
	echo
	labadmin_info "Applying persistence"
	labadmin_iptables-persistent
fi
