#!/usr/bin/env bash
#===================================================================================
#     FILE: misc/xmas
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Christmas congratulations for all users!"
	script_type="ssh"
	script_bg="force sub"
	script_admindeps=""
	script_hostdeps="beep terminator"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


# First logged user in X
u=($(labadmin_users-display | head -1))

# CHECK USERS
[ ! "${u[0]}" ] && labadmin_error "No users logged" 1


echo '#!/bin/bash
# Author: Sergio Lepore (https://github.com/sergiolepore)
(trap beep INT TERM HUP; beep -f261 -l500 -n -f349 -l500 -n -f349 -l250 -n -f392 -l250 -n -f349 -l250 -n -f329 -l250 -n -f293 -l500 -n -f293 -l500 -n -f293 -l500 -n -f392 -l500 -n -f392 -l250 -n -f440 -l250 -n -f392 -l250 -n -f349 -l250 -n -f329 -l500 -n -f329 -l500 -n -f329 -l500 -n -f440 -l500 -n -f440 -l250 -n -f493 -l250 -n -f440 -l250 -n -f392 -l250 -n -f349 -l500 -n -f293 -l500 -n -f261 -l250 -n -f261 -l250 -n -f293 -l500 -n -f392 -l500 -n -f329 -l500 -n -f349 -l1000 -n -f261 -l500 -n -f349 -l500 -n -f349 -l500 -n -f349 -l500 -n -f329 -l1000 -n -f329 -l500 -n -f349 -l500 -n -f329 -l500 -n -f293 -l500 -n -f261 -l1000 -n -f392 -l1000 -n -f440 -l500 -n -f392 -l250 -n -f392 -l250 -n -f349 -l250 -n -f349 -l250 -n -f523 -l500 -n -f261 -l500 -n -f261 -l250 -n -f261 -l250 -n -f293 -l500 -n -f392 -l500 -n -f329 -l500 -n -f349 -l1000) & 

trap "tput reset; tput cnorm; exit" 2
clear
tput civis
lin=2
col=$(($(tput cols) / 2))
c=$((col-1))
est=$((c-2))
color=0
tput setaf 2; tput bold

# Tree
for ((i=1; i<20; i+=2))
{
    tput cup $lin $col
    for ((j=1; j<=i; j++))
    {
        echo -n \*
    }
    let lin++
    let col--
}

tput sgr0; tput setaf 3

# Trunk
for ((i=1; i<=2; i++))
{
    tput cup $((lin++)) $c
    echo "mWm"
}
new_year=$(date +"%Y")
let new_year++
tput setaf 0; tput bold
tput cup $lin $((c - 6)); echo MERRY CHRISTMAS
tput cup $((lin + 1)) $((c - 10)); echo And lots of BASH in $new_year
let c++
k=1

# Lights and decorations
while true; do
    for ((i=1; i<=35; i++)) {
        # Turn off the lights
        [ $k -gt 1 ] && {
            tput setaf 2; tput bold
            tput cup ${line[$[k-1]$i]} ${column[$[k-1]$i]}; echo \*
            unset line[$[k-1]$i]; unset column[$[k-1]$i]  # Array cleanup
        }

        li=$((RANDOM % 9 + 3))
        start=$((c-li+2))
        co=$((RANDOM % (li-2) * 2 + 1 + start))
        tput setaf $color; tput bold   # Switch colors
        tput cup $li $co
        echo o
        line[$k$i]=$li
        column[$k$i]=$co
        color=$(((color+1)%8))
        # Flashing text
        sh=1
        for l in B A S H
        do
            tput cup $((lin+1)) $((c+sh))
            echo $l
            let sh++
            sleep 0.01
        done
    }
    k=$((k % 2 + 1))
done' > /tmp/labadmin-xmas.sh

labdmin_config_terminator "${u[0]}"
com="terminator -x bash -c \"/tmp/labadmin-xmas.sh\""
su -l "${u[0]}" -c "DISPLAY=${u[1]} xhost si:localuser:$(id -un)" &>/dev/null
su -l "${u[0]}" -c "DISPLAY=${u[1]} $com" 2>/dev/null

