#!/usr/bin/env bash
#===================================================================================
#     FILE: software/install
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Install package software silently"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM1: pass
    read_param "$script_id" 1 "Package path" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
pkg="$1"
echo 'Start-Process -FilePath "'"$pkg"'" -ArgumentList '\''/s'\'','\''/v"/qn"'\'' -Verb runas -Wait'
