#!/usr/bin/env bash
#===================================================================================
#     FILE: dfc/conf
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Replace DP configuration using .rdx file (works frozen and unfrozen)"
	script_type="winrm-ps"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: pass
    read_param "$script_id" 1 "DF password" "" "."
	# PARAM2: file
    read_param "$script_id" 2 "Remote .rdx file path" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
pass="$1"
rfile="$2"

echo 'DFC.exe '"${pass}"' /CFG="'"$rfile"'"
if ( $lastExitCode -eq 0 ) { echo "OK"
} else { echo "ERROR: $lastExitCode"}'
