#!/usr/bin/env bash
#===================================================================================
#     FILE: conf/time/set
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Set system timedate"
	script_type="ssh"
	script_bg="sub"
    script_admindeps=""
    script_hostdeps="hwclock(util-linux)"
    load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps" 
    return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    # PARAM2: date
    read_param "$script_id" 1 "Date (format YYYY-MM-DD, default local)" "$(date +%Y-%m-%d)" "^[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]$"
    # PARAM3: time
    read_param "$script_id" 2 "Hour (format HH:MM:SS, default local)" "$(date +%H:%M:%S)"  "^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$"
	return
fi



#=== EXEC SCRIPT ===================================================================
d="$1"
h="$2"

date "+%Y-%m-%d %T" -s "${d} ${h}"
hwclock -w
