#!/usr/bin/env bash
#===================================================================================
#     FILE: conf/labadmin/conf
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Update labadmin host config (sshport and sshpubkey) from lab config file"
	script_type="local"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps=""
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	# PARAM1: show
	read_param "$script_id" 1 "Lab config (lab name or absolute file path)" "" "."
	return
fi


#=== EXEC SCRIPT ===================================================================
lab_config="$1"
[ ${lab_config:0:1} != "/" ] && lab_config="${labs_path}/${lab_config}"

# CHECKS
if [ ! -f "${lab_config}" ]; then
	labadmin_error "$(echo "Can't access lab config file $lab_config" | tr -s "/")"
	echo "Available labs to use:"
	find "$labs_path" -type f | sed 's\'"${labs_path}"'\ \g'
	echo "Or specify your own file with absolute path"
	exit 1
fi


# UPDATE CONFIGS
(
	labadmin_info "Getting config values from $lab_conf"
	unset sshport sshpubkey sshprivatekey
	source "$lab_config"
	[ ! "$sshuser" ] && labadmin_error "Can't find sshuser value from lab config file" 1
	[ ! "$sshport" ] && labadmin_error "Can't find sshport value from lab config file" 1
	[ ! "$sshpubkey" ] && labadmin_error "Can't find sshpubkey value from lab config file" 1
	echo -e "sshuser: ${S_B}${sshuser}${S_R}"
	echo -e "sshport: ${S_B}${sshport}${S_R}"
	echo -e "sshpubkey: ${S_B}${sshpubkey}${S_R}"
	echo

	labdmin_ssh_host_comm "${labadmin_nhost}" '
sshport="'"$sshport"'"
sshuser="'"$sshuser"'"
sshpubkey="'"$sshpubkey"'"

# SET SSH PORT
labadmin_info "Setting SSH port"
if [ -f /etc/ssh/sshd_config ]; then
	sed -i "/^Port[[:blank:]]\+[0-9]\+/Id" /etc/ssh/sshd_config
	echo "Port $sshport" >> /etc/ssh/sshd_config
else
	labadmin_error "SSH config file /etc/ssh/sshd_config not exists" 
fi

# SET SSH PUBLIC KEY
labadmin_info "Setting public key for labadmin authentication"
sshhome="$(eval echo ~${sshuser})"
echo "$sshpubkey" > "${sshhome}/.ssh/authorized_keys"

'
)
