#!/usr/bin/env bash
#===================================================================================
#     FILE: conf/cron/show
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"		# Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
	script_desc="Show root crontab config"
	script_type="ssh"
	script_bg="sub"
	script_admindeps=""
	script_hostdeps="crontab(cron)"
	load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
	return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
	return
fi


#=== EXEC SCRIPT ===================================================================
crontab -l
