#!/usr/bin/env bash
#===================================================================================
#     FILE: misc/screenshot/show
#   AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#  LICENSE: GNU General Public License v3.0
#===================================================================================
script_id="$(echo ${BASH_SOURCE[0]} | sed 's\^'"$scripts_path"'/*\\g')"     # Script filename with relative script path

#=== LOAD INFO =====================================================================
if [ "$1" = "--load-scriptinfo" ]; then
    script_desc="Show screenshot animation for each host"
    script_type="admin+local+admin"
    script_bg="force sub"
    script_admindeps="feh"
    script_hostdeps="import(imagemagick)"
    load_scriptinfo "$script_id" "$script_desc" "$script_type" "$script_bg" "$script_admindeps" "$script_hostdeps"
    return

#=== READ PARAMS ===================================================================
elif [ "$1" = "--readparams" ]; then
    return
fi


#=== EXEC SCRIPT ===================================================================

# ADMIN EXEC STAGE1
if [ "${labadmin_script_type}" = "admin" ] && [ "${labadmin_script_type_state}" = "1" ]; then
    # CREATE TMP DIR
	export dir_img="$(mktemp -d "$labadmin_tmp_path/screenshot-display.XXXXXXXX")"
	labadmin_info "Creating temp directory $dir"

(   
    # Wait for first image created
    sleep 1
    n=0 
    while [ "$(find "$dir_img" -name "*.jpg" -size 0)" ]; do  
       	labadmin_info-list "Waiting for images..."
        sleep 1
        n=$((n+1))
        if [ "$n" -gt 5 ]; then
            labadmin_error-list "Skipping not responding hosts:"
            rm -v $(find "$dir_img" -name "*.jpg" -size 0)
        fi  
    done
    
    # Start imagen viewer tool
    feh -S filename -R 0.5 --title "%n" "$dir_img"/*.jpg

    # Remove dir 
    labadmin_info "Removing $dir_img"
    rm -rf "$dir_img"
)&


# LOCAL EXEC: 
elif [ "${labadmin_script_type}" = "local" ]; then
    export dir_img="$(ls -dt "$labadmin_tmp_path/screenshot-display"* | head -1)"
    export file_img="${dir_img}/HOST_${labadmin_nhost}.jpg"
    touch "$file_img"

    while true; do
        (
            [ ! -d "$dir_img" ] && exit
            labdmin_ssh_host_comm "${labadmin_nhost}" '
u=($(labadmin_users-display | head -1))
[ ! "${u[0]}" ] && labadmin_error "No users logged" 1
su -l "${u[0]}" -c "import -window root -display "${u[1]}" jpg:-"' > "${file_img}.tmp" && cp "${file_img}.tmp" "${file_img}"
)&
        sleep 0.5
    done


# ADMIN EXEC STAGE 2
elif [ "${labadmin_script_type}" = "admin" ] && [ "${labadmin_script_type_state}" = "2" ]; then
    dir_img="$(ls -dt "$labadmin_tmp_path/screenshot-display"* | head -1)/"
    read -p ""
    echo -e "Removing $dir_img"
    rm -rf "$dir_img"
fi

